name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'Backend/pyproject.toml'

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check --fix

      - name: Run Tests
        run: |
          echo "Add tests later"
